In [1]:
#Prgram to perform svd using python
import numpy as np
from scipy.linalg import svd
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
p,q,r=svd(a)
print("m1")
print(p)
print("m2")
print(q)
print("m3")
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
m1
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
m2
[  1.68481034e+01   1.06836951e+00   1.47280825e-16]
m3
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]
