In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import numpy as np
a=np.array([[2,3,4],[3,4,5],[6,7,3]])
print(a)

[[2 3 4]
 [3 4 5]
 [6 7 3]]


In [13]:
import numpy as np
a=np.zeros([3,3])
print(a)


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [14]:
import numpy as np
a=np.ones([2,2])
print(a)

[[ 1.  1.]
 [ 1.  1.]]


In [15]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
a=np.arange(2,9)
print(a)

[2 3 4 5 6 7 8]


In [28]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("first matrix")
print(a)
b=np.arange(9).reshape(3,3)
print("second matrix")
print(b)
c=np.dot(a,b)
print("product od 2 matrcies")
print(c)
t=np.transpose(c)
print("transpose of product matrix")
print(t)


first matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
second matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
product od 2 matrcies
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
transpose of product matrix
[[ 15  42  69]
 [ 18  54  90]
 [ 21  66 111]]


In [33]:
import numpy as np
a=np.arange(2,9,dtype=np.int)
print(a)

[2 3 4 5 6 7 8]


In [36]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
s=np.shape(a)
print(s)

[1 2 3 4 5]
(5,)


In [45]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
s=np.linspace(1,4,6)
print(s)

[1 2 3 4]
[ 1.   1.6  2.2  2.8  3.4  4. ]


In [44]:
import numpy as np
from scipy.linalg import svd
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
p,q,r=svd(a)
print("m1")
print(p)
print("m2")
print(q)
print("m3")
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
m1
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
m2
[  1.68481034e+01   1.06836951e+00   1.47280825e-16]
m3
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]
